import React, { useState, useEffect, createContext, useContext } from 'react'; import { createRoot } from 'react-dom/client'; import { BrowserRouter, useNavigate, useParams, Link, Routes, Route } from 'react-router-dom'; import './styles.css';
const API = 'https://dinehub-api-2ed2.onrender.com/api';
const AuthContext = createContext();
function useAuth() { return useContext(AuthContext) }
function AuthProvider({ children }) { const [auth, setAuth] = useState(() => JSON.parse(localStorage.getItem('dinehub_auth') || 'null')); const login = x => { localStorage.setItem('dinehub_auth', JSON.stringify(x)); setAuth(x) }; const logout = () => { localStorage.removeItem('dinehub_auth'); setAuth(null) }; return <AuthContext.Provider value={{ auth, login, logout }}>{children}</AuthContext.Provider> }
async function api(path, opt = {}) {
  const a = JSON.parse(
    localStorage.getItem('dinehub_auth') || 'null'
  );

  const res = await fetch(API + path, {
    headers: {
      'Content-Type': 'application/json',
      ...(a?.token
        ? { Authorization: `Bearer ${a.token}` }
        : {})
    },
    ...opt
  });

  const data = await res.json();

  if (!res.ok) {
    throw Error(data.message || 'Request failed');
  }

  return data;
}
function Layout() { const { auth, logout } = useAuth(); return <><header><Link className="brand" to="/">🍽️ Dine<span>Hub</span></Link><nav><Link to="/">Home</Link><Link to="/restaurants">Restaurants</Link>{auth && <Link to="/bookings">My Bookings</Link>}{auth?.user.role === 'admin' && <Link to="/admin">Admin</Link>}{auth ? <button className="linkbtn" onClick={logout}>Logout</button> : <Link to="/login">Login</Link>}</nav></header><main><Routes><Route path="/" element={<Home />} /><Route path="/restaurants" element={<Restaurants />} /><Route path="/restaurants/:id" element={<Restaurant />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/bookings" element={<Bookings />} /><Route path="/admin" element={<Admin />} /></Routes></main><footer>© 2026 DineHub · Discover. Reserve. Dine.</footer></> }
function Home() { const [q, setQ] = useState(''); const nav = useNavigate(); return <section className="hero"><div><p className="eyebrow">YOUR TABLE, YOUR WAY</p><h1>Find the perfect table for your next <span>great meal.</span></h1><p className="lead">Discover restaurants, explore menus and reserve tables in a few clicks.</p><div className="search"><input placeholder="Search restaurant, cuisine or city..." value={q} onChange={e => setQ(e.target.value)} /><button onClick={() => nav('/restaurants?q=' + encodeURIComponent(q))}>Search</button></div><div className="stats"><div><b>50+</b><small>Restaurants</small></div><div><b>1K+</b><small>Happy diners</small></div><div><b>4.8★</b><small>Average rating</small></div></div></div><div className="hero-card"><div className="hero-image" /><div><b>Tonight's pick</b><h3>The Urban Fork</h3><p>Continental · 4.7★ · $$$</p><Link className="btn" to="/restaurants/r1">View restaurant</Link></div></div></section> }
function Restaurants() { const [data, setData] = useState([]); const [loading, setLoading] = useState(true); const params = new URLSearchParams(location.search); const [q, setQ] = useState(params.get('q') || ''); useEffect(() => { api('/restaurants?q=' + encodeURIComponent(q)).then(setData).finally(() => setLoading(false)) }, []); return <section className="page"><div className="section-head"><div><p className="eyebrow">EXPLORE</p><h2>Restaurants you'll love</h2></div><input className="smallsearch" value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === 'Enter' && api('/restaurants?q=' + encodeURIComponent(q)).then(setData)} placeholder="Search..." /></div>{loading ? <p>Loading restaurants...</p> : <div className="grid">{data.map(r => <article className="card" key={r._id}><img src={r.image} /><div className="cardbody"><div className="row"><span className="pill">{r.cuisine}</span><span>★ {r.rating}</span></div><h3>{r.name}</h3><p>{r.city} · {'$'.repeat(r.priceLevel)}</p><p className="muted">{r.description}</p><Link className="btn full" to={'/restaurants/' + r._id}>View & book</Link></div></article>)}</div>}</section> }
function Restaurant() { const { id } = useParams(); const [r, setR] = useState(null); const [form, setForm] = useState({ tableNumber: '', date: '', time: '19:00', guests: 2 }); const [msg, setMsg] = useState(''); const { auth } = useAuth(); const nav = useNavigate(); useEffect(() => { api('/restaurants/' + id).then(setR) }, [id]); if (!r) return <section className="page">Loading...</section>; async function book(e) { e.preventDefault(); if (!auth) return nav('/login'); try { await api('/bookings', { method: 'POST', body: JSON.stringify({ ...form, restaurantId: r._id, restaurantName: r.name }) }); setMsg('Booking confirmed! Check My Bookings.') } catch (e) { setMsg(e.message) } } return <section className="page detail"><img className="detailimg" src={r.image} /><div><span className="pill">{r.cuisine}</span><h2>{r.name}</h2><p>★ {r.rating} · {r.city} · {r.address}</p><p>{r.description}</p><div className="bookingbox"><h3>Reserve your table</h3><form onSubmit={book}><label>Date<input required type="date" min={new Date().toISOString().slice(0, 10)} value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} /></label><label>Time<input required type="time" value={form.time} onChange={e => setForm({ ...form, time: e.target.value })} /></label><label>Guests<select value={form.guests} onChange={e => setForm({ ...form, guests: e.target.value })}>{[1, 2, 3, 4, 5, 6, 8].map(n => <option key={n}>{n}</option>)}</select></label><label>Table<select required value={form.tableNumber} onChange={e => setForm({ ...form, tableNumber: e.target.value })}><option value="">Select</option>{r.tables.filter(t => t.seats >= form.guests).map(t => <option key={t.number} value={t.number}>Table {t.number} · {t.seats} seats</option>)}</select></label><button className="btn full">Confirm booking</button></form>{msg && <p className="success">{msg}</p>}</div></div></section> }
function Login() { const { login } = useAuth(); const nav = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [err, setErr] = useState(''); async function submit(e) { e.preventDefault(); try { const x = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); login(x); nav(x.user.role === 'admin' ? '/admin' : '/') } catch (e) { setErr(e.message) } } return <AuthForm title="Welcome back" submit={submit} error={err} fields={<><input type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} required /><input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required /></>} button="Login"><p>New here? <Link to="/register">Create an account</Link></p></AuthForm> }
function Register() { const { login } = useAuth(); const nav = useNavigate(); const [f, setF] = useState({ name: '', email: '', password: '' }); const [err, setErr] = useState(''); async function submit(e) { e.preventDefault(); try { const x = await api('/auth/register', { method: 'POST', body: JSON.stringify(f) }); login(x); nav('/') } catch (e) { setErr(e.message) } } return <AuthForm title="Create your DineHub account" submit={submit} error={err} fields={<><input placeholder="Full name" value={f.name} onChange={e => setF({ ...f, name: e.target.value })} required /><input type="email" placeholder="Email" value={f.email} onChange={e => setF({ ...f, email: e.target.value })} required /><input type="password" placeholder="Password" minLength="6" value={f.password} onChange={e => setF({ ...f, password: e.target.value })} required /></>} button="Create account"><p>Already registered? <Link to="/login">Login</Link></p></AuthForm> }
function AuthForm({ title, submit, error, fields, button, children }) { return <section className="auth"><form onSubmit={submit} className="authbox"><p className="eyebrow">DINEHUB</p><h2>{title}</h2>{fields}<button className="btn full">{button}</button>{error && <p className="error">{error}</p>}{children}</form></section> }
function Bookings() { const { auth } = useAuth(); const [data, setData] = useState([]); useEffect(() => { if (auth) api('/bookings').then(setData) }, [auth]); if (!auth) return <NavigateLogin />; return <section className="page"><p className="eyebrow">YOUR RESERVATIONS</p><h2>My Bookings</h2>{data.length ? <div className="bookinglist">{data.map(b => <div className="booking" key={b._id}><div><span className="pill">{b.status}</span><h3>{b.restaurantName}</h3><p>Table {b.tableNumber} · {b.guests} guests</p></div><strong>{b.date}<br />{b.time}</strong></div>)}</div> : <div className="empty">No bookings yet. <Link to="/restaurants">Explore restaurants</Link></div>}</section> }
function NavigateLogin() { const nav = useNavigate(); useEffect(() => nav('/login'), []); return null }
function Admin() { const { auth } = useAuth(); const [bs, setBs] = useState([]); const [msg, setMsg] = useState(''); const [f, setF] = useState({ name: '', cuisine: '', city: '', address: '', description: '', image: '' }); useEffect(() => { if (auth?.user.role === 'admin') api('/admin/bookings').then(setBs) }, [auth]); if (auth?.user.role !== 'admin') return <NavigateLogin />; async function add(e) { e.preventDefault(); try { await api('/admin/restaurants', { method: 'POST', body: JSON.stringify(f) }); setMsg('Restaurant added successfully'); setF({ name: '', cuisine: '', city: '', address: '', description: '', image: '' }) } catch (e) { setMsg(e.message) } } return <section className="page"><p className="eyebrow">ADMIN</p><h2>Management Dashboard</h2><div className="admin-grid"><div className="panel"><h3>Add restaurant</h3><form onSubmit={add}>{Object.keys(f).map(k => <input key={k} placeholder={k[0].toUpperCase() + k.slice(1)} value={f[k]} onChange={e => setF({ ...f, [k]: e.target.value })} required={k !== 'image'} />)}<button className="btn full">Add restaurant</button>{msg && <p className="success">{msg}</p>}</form></div><div className="panel"><h3>Recent bookings ({bs.length})</h3>{bs.map(b => <div className="adminrow" key={b._id}><b>{b.restaurantName}</b><span>{b.date} · Table {b.tableNumber}</span></div>)}{!bs.length && <p className="muted">No bookings yet.</p>}</div></div></section> }
function App() { return <AuthProvider><Layout /></AuthProvider> } createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
