import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
dotenv.config();
const app=express(); app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||5000; const SECRET=process.env.JWT_SECRET||'dinehub_secret';
const Restaurant=new mongoose.Schema({name:String,cuisine:String,city:String,address:String,description:String,image:String,rating:{type:Number,default:4.5},priceLevel:{type:Number,default:2},tables:[{number:Number,seats:Number,available:{type:Boolean,default:true}}]},{timestamps:true});
const User=new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,default:'user'}},{timestamps:true});
const Booking=new mongoose.Schema({userId:mongoose.Schema.Types.ObjectId,restaurantId:mongoose.Schema.Types.ObjectId,restaurantName:String,tableNumber:Number,date:String,time:String,guests:Number,status:{type:String,default:'confirmed'}},{timestamps:true});
const RestaurantModel=mongoose.model('Restaurant',Restaurant),UserModel=mongoose.model('User',User),BookingModel=mongoose.model('Booking',Booking);
let memoryRestaurants=[{_id:'r1',name:'The Urban Fork',cuisine:'Continental',city:'Lucknow',address:'Hazratganj, Lucknow',description:'Modern dining with continental favourites and a relaxed ambience.',image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80',rating:4.7,priceLevel:3,tables:[{number:1,seats:2,available:true},{number:2,seats:4,available:true},{number:3,seats:6,available:true}]},{_id:'r2',name:'Spice Route',cuisine:'Indian',city:'Lucknow',address:'Gomti Nagar, Lucknow',description:'Regional Indian flavours, family dining and warm hospitality.',image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',rating:4.8,priceLevel:2,tables:[{number:1,seats:2,available:true},{number:2,seats:4,available:true},{number:3,seats:4,available:true}]},{_id:'r3',name:'Sushi Sakura',cuisine:'Japanese',city:'Delhi',address:'Saket, New Delhi',description:'Fresh sushi, ramen and Japanese-inspired dining.',image:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=80',rating:4.6,priceLevel:3,tables:[{number:1,seats:2,available:true},{number:2,seats:2,available:true},{number:3,seats:4,available:true}]}];
let memoryUsers=[]; let memoryBookings=[];
const useMemory=()=>mongoose.connection.readyState!==1;
function token(user){return jwt.sign({id:String(user._id),role:user.role,name:user.name},SECRET,{expiresIn:'7d'})}
function auth(req,res,next){const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({message:'Login required'});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
async function restaurants(){return useMemory()?memoryRestaurants:RestaurantModel.find().lean()}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'DineHub API'}));
app.get('/api/restaurants',async(req,res)=>{let data=await restaurants();const q=(req.query.q||'').toLowerCase();if(q)data=data.filter(r=>`${r.name} ${r.cuisine} ${r.city}`.toLowerCase().includes(q));res.json(data)});
app.get('/api/restaurants/:id',async(req,res)=>{const data=await restaurants();const r=data.find(x=>String(x._id)===req.params.id);if(!r)return res.status(404).json({message:'Restaurant not found'});res.json(r)});
app.post('/api/auth/register',async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});let exists=useMemory()?memoryUsers.find(u=>u.email===email.toLowerCase()):await UserModel.findOne({email:email.toLowerCase()});if(exists)return res.status(409).json({message:'Email already registered'});const u={_id:new mongoose.Types.ObjectId(),name,email:email.toLowerCase(),password:await bcrypt.hash(password,10),role:'user'};if(useMemory())memoryUsers.push(u);else await UserModel.create(u);res.status(201).json({token:token(u),user:{name:u.name,email:u.email,role:u.role}})});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;let u=useMemory()?memoryUsers.find(x=>x.email===email?.toLowerCase()):await UserModel.findOne({email:email?.toLowerCase()});if(!u&&email==='admin@dinehub.com'&&password==='admin123'){u={_id:new mongoose.Types.ObjectId('507f1f77bcf86cd799439011'),name:'DineHub Admin',email,role:'admin',password:await bcrypt.hash(password,10)};if(useMemory())memoryUsers.push(u);else await UserModel.create(u)}if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({message:'Invalid email or password'});res.json({token:token(u),user:{name:u.name,email:u.email,role:u.role}})});
app.get('/api/bookings',auth,async(req,res)=>{const data=useMemory()?memoryBookings:await BookingModel.find({userId:req.user.id}).sort({createdAt:-1}).lean();res.json(data)});
app.post('/api/bookings',auth,async(req,res)=>{const {restaurantId,restaurantName,tableNumber,date,time,guests}=req.body;if(!restaurantId||!tableNumber||!date||!time||!guests)return res.status(400).json({message:'Please fill all booking fields'});const b={_id:new mongoose.Types.ObjectId(),userId:req.user.id,restaurantId,restaurantName,tableNumber:Number(tableNumber),date,time,guests:Number(guests),status:'confirmed',createdAt:new Date()};if(useMemory())memoryBookings.unshift(b);else await BookingModel.create(b);res.status(201).json(b)});
app.get('/api/admin/bookings',auth,async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin only'});res.json(useMemory()?memoryBookings:await BookingModel.find().sort({createdAt:-1}).lean())});
app.post('/api/admin/restaurants',auth,async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({message:'Admin only'});const r={_id:new mongoose.Types.ObjectId(),tables:[{number:1,seats:2,available:true},{number:2,seats:4,available:true}],rating:4.5,priceLevel:2,...req.body};if(useMemory())memoryRestaurants.push(r);else await RestaurantModel.create(r);res.status(201).json(r)});
async function seed(){if(useMemory())return;if(await RestaurantModel.countDocuments()===0)await RestaurantModel.insertMany(memoryRestaurants.map(({_id,...r})=>r));if(!await UserModel.findOne({email:'admin@dinehub.com'}))await UserModel.create({name:'DineHub Admin',email:'admin@dinehub.com',password:await bcrypt.hash('admin123',10),role:'admin'})}
mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/dinehub').then(()=>{console.log('MongoDB connected');seed()}).catch(e=>console.log('MongoDB unavailable; using demo memory mode:',e.message));
app.listen(PORT,()=>console.log(`DineHub API running on http://localhost:${PORT}`));
